
"""Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CatalogSourceStatus(str, Enum):
    """Operational status of a catalog source. - `available`: The source is functioning correctly and models can be retrieved - `partially-available`: The source loaded some models successfully but encountered errors with others - `error`: The source is experiencing issues and cannot provide models - `disabled`: The source has been intentionally disabled
    """

    """
    allowed enum values
    """
    AVAILABLE = "available"
    PARTIALLY_MINUS_AVAILABLE = "partially-available"
    ERROR = "error"
    DISABLED = "disabled"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CatalogSourceStatus from a JSON string"""
        return cls(json.loads(json_str))


