
"""Catalog REST API

REST API for Kubeflow Hub Catalog

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict
from typing_extensions import Self

from catalog_openapi.models.mcp_resource_recommendation_high import MCPResourceRecommendationHigh
from catalog_openapi.models.mcp_resource_recommendation_minimal import MCPResourceRecommendationMinimal
from catalog_openapi.models.mcp_resource_recommendation_recommended import MCPResourceRecommendationRecommended


class MCPResourceRecommendation(BaseModel):
    """MCPResourceRecommendation
    """ # noqa: E501
    minimal: MCPResourceRecommendationMinimal | None = None
    recommended: MCPResourceRecommendationRecommended | None = None
    high: MCPResourceRecommendationHigh | None = None
    __properties: ClassVar[list[str]] = ["minimal", "recommended", "high"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of MCPResourceRecommendation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of minimal
        if self.minimal:
            _dict["minimal"] = self.minimal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recommended
        if self.recommended:
            _dict["recommended"] = self.recommended.to_dict()
        # override the default output from pydantic by calling `to_dict()` of high
        if self.high:
            _dict["high"] = self.high.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of MCPResourceRecommendation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "minimal": MCPResourceRecommendationMinimal.from_dict(obj["minimal"]) if obj.get("minimal") is not None else None,
            "recommended": MCPResourceRecommendationRecommended.from_dict(obj["recommended"]) if obj.get("recommended") is not None else None,
            "high": MCPResourceRecommendationHigh.from_dict(obj["high"]) if obj.get("high") is not None else None
        })
        return _obj


