apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- model-registry-configmap.yaml
- model-registry-deployment.yaml
- model-registry-service.yaml
- model-registry-sa.yaml
images:
- name: ghcr.io/kubeflow/model-registry
  newName: ghcr.io/kubeflow/model-registry
  newTag: v0.2.15
