apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - path: model-registry-ui-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: model-registry-ui-deployment
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: model-registry-bff-deployment