---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-async-upload-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: async-upload
          image: kubeflow/model-registry-async-job:local
          env:
            # ---- Source ----------
            - name: MODEL_SYNC_SOURCE_TYPE
              value: "s3"
            - name: MODEL_SYNC_SOURCE_AWS_BUCKET
              value: "default"
            - name: MODEL_SYNC_SOURCE_AWS_KEY
              value: "my-model"
            - name: MODEL_SYNC_SOURCE_AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: MODEL_SYNC_SOURCE_AWS_SECRET_ACCESS_KEY
              value: "minioadmin"
            - name: MODEL_SYNC_SOURCE_AWS_ENDPOINT
              value: "http://minio.minio.svc.cluster.local:9000"

            # ---- Destination -----
            - name: MODEL_SYNC_DESTINATION_TYPE
              value: "oci"
            - name: MODEL_SYNC_DESTINATION_OCI_URI
              value: "oci://localhost:5000/my-model"

            # ---- Model Params ----
            - name: MODEL_SYNC_MODEL_NAME
              value: "my-model"
            - name: MODEL_SYNC_MODEL_VERSION
              value: "1.0.0"
            - name: MODEL_SYNC_MODEL_FORMAT
              value: "onnx"
            - name: MODEL_SYNC_MODEL_FORMAT_VERSION
              value: "1"

            # ---- Model Registry Client Params ----
            - name: MODEL_SYNC_REGISTRY_SERVER_ADDRESS
              value: "http://model-registry-service.kubeflow.svc.cluster.local"
            - name: MODEL_SYNC_REGISTRY_PORT
              value: "8080"
            - name: MODEL_SYNC_REGISTRY_AUTHOR
              value: "Alice Bob"
            - name: MODEL_SYNC_REGISTRY_USER_TOKEN
              value: "super-secret"

            # ...
