---
apiVersion: v1
kind: Secret
metadata:
  name: my-s3-credentials
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_BUCKET: default
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
---
apiVersion: v1
kind: Secret
metadata:
  name: my-oci-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths": {"distribution-registry-test-service.default.svc.cluster.local:5001": {"auth": "base64(username:password)","email": "user@example.com"}}}'
  ACCESS_TYPE: ["Push", "Pull"]
  OCI_HOST: distribution-registry-test-service.default.svc.cluster.local:5001
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-async-upload-job
spec:
  template:
    spec:
      volumes:
        - name: source-credentials
          secret:
            secretName: my-s3-credentials
        - name: destination-credentials
          secret:
            secretName: my-oci-credentials
      restartPolicy: Never
      containers:
        - name: async-upload
          image: kubeflow/model-registry-async-job:local
          volumeMounts:
            - name: source-credentials
              readOnly: true
              mountPath: "/opt/creds/source"
            - name: destination-credentials
              readOnly: true
              mountPath: "/opt/creds/destination"
          env:
            - name: HTTP_PROXY
              value: ""
            - name: HTTPS_PROXY
              value: ""
            - name: NO_PROXY
              value: "minio.minio.svc.cluster.local,*.svc.cluster.local"
            # ---- Source ----------
            - name: MODEL_SYNC_SOURCE_TYPE
              value: "s3"
            - name: MODEL_SYNC_SOURCE_AWS_KEY
              value: "my-model"
            - name: MODEL_SYNC_SOURCE_S3_CREDENTIALS_PATH
              value: "/opt/creds/source"

            # ---- Destination -----
            - name: MODEL_SYNC_DESTINATION_TYPE
              value: "oci"
            - name: MODEL_SYNC_DESTINATION_OCI_URI
              value: "oci://distribution-registry-test-service.default.svc.cluster.local:5001/my-model:latest"
            - name: MODEL_SYNC_DESTINATION_OCI_CREDENTIALS_PATH
              value: "/opt/creds/destination"

            # ---- Model Params ----
            - name: MODEL_SYNC_MODEL_ID
              value: "1"
            - name: MODEL_SYNC_MODEL_VERSION_ID
              value: "3"
            - name: MODEL_SYNC_MODEL_ARTIFACT_ID
              value: "6"

            # ---- Model Registry Client Params ----
            - name: MODEL_SYNC_REGISTRY_SERVER_ADDRESS
              value: "http://model-registry-service.kubeflow.svc.cluster.local"
            - name: MODEL_SYNC_REGISTRY_PORT
              value: "8080"
            - name: MODEL_SYNC_REGISTRY_AUTHOR
              value: "Alice Bob"
            - name: MODEL_SYNC_REGISTRY_USER_TOKEN
              value: "super-secret"

            # ...
