---
apiVersion: v1
kind: Secret
metadata:
  name: my-s3-credentials
data:
  AWS_ACCESS_KEY_ID: suPeR-SecReT
  AWS_SECRET_ACCESS_KEY: suPeR-SecReT
  AWS_BUCKET: bucket-1
  AWS_KEY: my-model
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: my-oci-credentials
data:
  .dockerconfigjson: '{"auths": {"registry.example.com": {"auth": "base64(username:password)","email": "user@example.com"}}}'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-async-upload-job
spec:
  template:
    spec:
      volumes:
        - name: source-credentials
          secret:
            secretName: my-s3-credentials
        - name: destination-credentials
          secret:
            secretName: my-oci-credentials
      restartPolicy: Never
      containers:
        - name: async-upload
          image: kubeflow/model-registry-async-job:local
          env:
            # ---- Source ----------
            - name: MODEL_SYNC_SOURCE_TYPE
              value: "s3"
            - name: MODEL_SYNC_SOURCE_S3_CREDENTIALS_PATH
              value: "/opt/creds/source"

            # ---- Destination -----
            - name: MODEL_SYNC_DESTINATION_TYPE
              value: "oci"
            - name: MODEL_SYNC_DESTINATION_OCI_CREDENTIALS_PATH
              value: "/opt/creds/destination"

            # ---- Model Params ----
            - name: MODEL_SYNC_MODEL_ID
              value: "1"
            - name: MODEL_SYNC_MODEL_VERSION_ID
              value: "3"
            - name: MODEL_SYNC_MODEL_ARTIFACT_ID
              value: "4"

            # ---- Model Registry Client Params ----
            - name: MODEL_SYNC_REGISTRY_SERVER_ADDRESS
              value: "http://model-registry-service.kubeflow.svc.cluster.local"
            - name: MODEL_SYNC_REGISTRY_PORT
              value: "8080"
            - name: MODEL_SYNC_REGISTRY_AUTHOR
              value: "Alice Bob"
            - name: MODEL_SYNC_REGISTRY_USER_TOKEN
              value: "super-secret"

            # ...

          volumeMounts:
            - name: source-credentials
              readOnly: true
              mountPath: "/opt/creds/source"
            - name: destination-credentials
              readOnly: true
              mountPath: "/opt/creds/destination"
