version: '3.4'
services:
  mlmd-server:
    image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
    container_name: mlmd-server
    ports:
      - "9090:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./test/config/ml-metadata:/tmp/shared
  model-registry:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["proxy", "--hostname", "0.0.0.0", "--mlmd-hostname", "mlmd-server", "--mlmd-port", "8080"]
    container_name: model-registry
    ports:
      - "8080:8080"
    depends_on:
      - mlmd-server
