apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth-pol-bff.yaml
- dest-rule-bff.yaml
namespace: kubeflow
commonLabels:
  app: model-registry-bff
  kustomize.component: model-registry-bff
