apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name==\postgresql\)].port}
    name: model-registry-db
  spec:
    ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      appProtocol: tcp
      targetPort: 5432
    selector:
      name: model-registry-db
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: model-registry-db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: model-registry-db
  spec:
    replicas: 1
    revisionHistoryLimit: 0
    selector:
      matchLabels:
        name: model-registry-db
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: model-registry-db
          sidecar.istio.io/inject: "false"
      spec:
        containers:
        - env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: model-registry-db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: model-registry-db
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: database-name
                name: model-registry-db
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          image: postgres:16
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "/usr/bin/pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
            initialDelaySeconds: 30
            timeoutSeconds: 2
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "psql -w -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: model-registry-db-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: model-registry-db-data
          persistentVolumeClaim:
            claimName: model-registry-db
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: model-registry-db
  stringData:
    database-name: "model-registry"
    database-password: "TheBlurstOfTimes"
    database-user: "mlmduser"
kind: List
metadata: {}
