/*
Model Registry REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WithBaseResourceCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithBaseResourceCreate{}

// WithBaseResourceCreate struct for WithBaseResourceCreate
type WithBaseResourceCreate struct {
	// The client provided name of the artifact. This field is optional. If set, it must be unique among all the artifacts of the same artifact type within a database instance and cannot be changed once set.
	Name *string `json:"name,omitempty"`
}

// NewWithBaseResourceCreate instantiates a new WithBaseResourceCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithBaseResourceCreate() *WithBaseResourceCreate {
	this := WithBaseResourceCreate{}
	return &this
}

// NewWithBaseResourceCreateWithDefaults instantiates a new WithBaseResourceCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithBaseResourceCreateWithDefaults() *WithBaseResourceCreate {
	this := WithBaseResourceCreate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WithBaseResourceCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithBaseResourceCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WithBaseResourceCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WithBaseResourceCreate) SetName(v string) {
	o.Name = &v
}

func (o WithBaseResourceCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithBaseResourceCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableWithBaseResourceCreate struct {
	value *WithBaseResourceCreate
	isSet bool
}

func (v NullableWithBaseResourceCreate) Get() *WithBaseResourceCreate {
	return v.value
}

func (v *NullableWithBaseResourceCreate) Set(val *WithBaseResourceCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableWithBaseResourceCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableWithBaseResourceCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithBaseResourceCreate(val *WithBaseResourceCreate) *NullableWithBaseResourceCreate {
	return &NullableWithBaseResourceCreate{value: val, isSet: true}
}

func (v NullableWithBaseResourceCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithBaseResourceCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
