import {
  ModelTransferJob,
  ModelTransferJobDestinationType,
  ModelTransferJobList,
  ModelTransferJobSourceType,
  ModelTransferJobStatus,
  ModelTransferJobUploadIntent,
} from '~/app/types';

export const mockModelTransferJob = (partial?: Partial<ModelTransferJob>): ModelTransferJob => ({
  id: '1',
  name: 'model-transfer-job-1',
  description: 'Transfer job for fraud detection model',
  source: {
    type: ModelTransferJobSourceType.S3,
    bucket: 'source-bucket',
    key: 'models/fraud-detection/v1',
    region: 'us-east-1',
  },
  destination: {
    type: ModelTransferJobDestinationType.S3,
    bucket: 'destination-bucket',
    key: 'models/fraud-detection/v1',
    region: 'us-west-2',
  },
  uploadIntent: ModelTransferJobUploadIntent.CREATE_VERSION,
  registeredModelId: '1',
  registeredModelName: 'Fraud Detection Model',
  modelVersionId: '1',
  modelVersionName: 'v1.0.0',
  modelArtifactId: '1',
  modelArtifactName: 'fraud-detection-artifact',
  status: ModelTransferJobStatus.COMPLETED,
  createTimeSinceEpoch: '1712234877179',
  lastUpdateTimeSinceEpoch: '1712234877179',
  ...partial,
});

export const mockModelTransferJobList = (
  partial?: Partial<ModelTransferJobList>,
): ModelTransferJobList => ({
  items: [
    mockModelTransferJob({}),
    mockModelTransferJob({
      id: '2',
      name: 'model-transfer-job-2',
      description: 'Transfer job for image classification model',
      source: {
        type: ModelTransferJobSourceType.OCI,
        uri: 'quay.io/ml-models/image-classifier:v1',
        registry: 'quay.io',
      },
      destination: {
        type: ModelTransferJobDestinationType.OCI,
        uri: 'registry.internal.io/models/image-classifier:v1',
        registry: 'registry.internal.io',
      },
      uploadIntent: ModelTransferJobUploadIntent.CREATE_MODEL,
      registeredModelId: '2',
      registeredModelName: 'Image Classification Model',
      status: ModelTransferJobStatus.RUNNING,
      createTimeSinceEpoch: '1712234900000',
      lastUpdateTimeSinceEpoch: '1712234950000',
    }),
    mockModelTransferJob({
      id: '3',
      name: 'model-transfer-job-3',
      description: 'Transfer job from URI source',
      source: {
        type: ModelTransferJobSourceType.URI,
        uri: 'https://huggingface.co/models/llama-2-7b/resolve/main/model.safetensors',
      },
      destination: {
        type: ModelTransferJobDestinationType.S3,
        bucket: 'model-storage',
        key: 'llm/llama-2-7b',
        region: 'us-east-1',
      },
      uploadIntent: ModelTransferJobUploadIntent.UPDATE_ARTIFACT,
      registeredModelId: '3',
      registeredModelName: 'Llama 2 7B',
      modelVersionId: '3',
      modelVersionName: 'main',
      modelArtifactId: '3',
      modelArtifactName: 'llama-2-7b-artifact',
      status: ModelTransferJobStatus.PENDING,
      createTimeSinceEpoch: '1712235000000',
      lastUpdateTimeSinceEpoch: '1712235000000',
    }),
    mockModelTransferJob({
      id: '4',
      name: 'model-transfer-job-4',
      description: 'Failed transfer job',
      status: ModelTransferJobStatus.FAILED,
      errorMessage: 'Connection timeout while uploading to destination bucket',
      createTimeSinceEpoch: '1712230000000',
      lastUpdateTimeSinceEpoch: '1712231000000',
    }),
  ],
  size: 4,
  pageSize: 10,
  nextPageToken: '',
  ...partial,
});
