"""Model Registry REST API.

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mr_openapi.models.model_artifact_update import ModelArtifactUpdate


class TestModelArtifactUpdate(unittest.TestCase):
    """ModelArtifactUpdate unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelArtifactUpdate:
        """Test ModelArtifactUpdate
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `ModelArtifactUpdate`
        """
        model = ModelArtifactUpdate()
        if include_optional:
            return ModelArtifactUpdate(
                custom_properties = {
                    'key' : null
                    },
                description = '',
                external_id = '',
                uri = '',
                state = 'UNKNOWN',
                model_format_name = '',
                storage_key = '',
                storage_path = '',
                model_format_version = '',
                service_account_name = ''
            )
        else:
            return ModelArtifactUpdate(
        )
        """

    def testModelArtifactUpdate(self):
        """Test ModelArtifactUpdate."""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
