"""Model Registry REST API.

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mr_openapi.models.base_resource_create import BaseResourceCreate


class TestBaseResourceCreate(unittest.TestCase):
    """BaseResourceCreate unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResourceCreate:
        """Test BaseResourceCreate
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `BaseResourceCreate`
        """
        model = BaseResourceCreate()
        if include_optional:
            return BaseResourceCreate(
                custom_properties = {
                    'key' : null
                    },
                description = '',
                external_id = '',
                name = ''
            )
        else:
            return BaseResourceCreate(
        )
        """

    def testBaseResourceCreate(self):
        """Test BaseResourceCreate."""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
