*** Keywords ***
I create a RegisteredModel having
    [Arguments]    ${name}
    # TODO: implement keyword "I create a RegisteredModel having".
    Fail    Not Implemented


I create a child ModelVersion having
    [Arguments]    ${registeredModelID}    ${name}
    # TODO: implement keyword "I create a child ModelVersion having".
    Fail    Not Implemented


I create a child ModelArtifact having
    [Arguments]    ${modelversionId}    ${uri}
    # TODO: implement keyword "I create a child ModelArtifact having".
    Fail    Not Implemented
