# coding: utf-8

"""
    Model Registry REST API

    REST API for Model Registry to create and manage ML model metadata

    The version of the OpenAPI document: v1alpha3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from mr_openapi.models.doc_artifact import DocArtifact
from mr_openapi.models.model_artifact import ModelArtifact
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

ARTIFACT_ONE_OF_SCHEMAS = ["DocArtifact", "ModelArtifact"]

class Artifact(BaseModel):
    """
    A metadata Artifact Entity.
    """
    # data type: ModelArtifact
    oneof_schema_1_validator: Optional[ModelArtifact] = None
    # data type: DocArtifact
    oneof_schema_2_validator: Optional[DocArtifact] = None
    if TYPE_CHECKING:
        actual_instance: Union[DocArtifact, ModelArtifact]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(ARTIFACT_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    discriminator_value_class_map = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Artifact.construct()
        error_messages = []
        match = 0
        # validate data type: ModelArtifact
        if not isinstance(v, ModelArtifact):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelArtifact`")
        else:
            match += 1
        # validate data type: DocArtifact
        if not isinstance(v, DocArtifact):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocArtifact`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Artifact with oneOf schemas: DocArtifact, ModelArtifact. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Artifact with oneOf schemas: DocArtifact, ModelArtifact. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Artifact:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Artifact:
        """Returns the object represented by the json string"""
        instance = Artifact.construct()
        error_messages = []
        match = 0

        # deserialize data into ModelArtifact
        try:
            instance.actual_instance = ModelArtifact.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DocArtifact
        try:
            instance.actual_instance = DocArtifact.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Artifact with oneOf schemas: DocArtifact, ModelArtifact. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Artifact with oneOf schemas: DocArtifact, ModelArtifact. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


