# coding: utf-8

"""
    Model Registry REST API

    REST API for Model Registry to create and manage ML model metadata

    The version of the OpenAPI document: v1alpha3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class MetadataStringValue(BaseModel):
    """
    A string property value.  # noqa: E501
    """
    string_value: StrictStr = Field(...)
    metadata_type: StrictStr = Field(..., alias="metadataType")
    __properties = ["string_value", "metadataType"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MetadataStringValue:
        """Create an instance of MetadataStringValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MetadataStringValue:
        """Create an instance of MetadataStringValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MetadataStringValue.parse_obj(obj)

        _obj = MetadataStringValue.parse_obj({
            "string_value": obj.get("string_value"),
            "metadata_type": obj.get("metadataType") if obj.get("metadataType") is not None else 'MetadataStringValue'
        })
        return _obj


