/*
Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the McpServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpServer{}

// McpServer An MCP (Model Context Protocol) server that provides tools for AI agents.
type McpServer struct {
	// Unique identifier for the MCP server.
	Id string `json:"id"`
	// Human-readable name of the MCP server.
	Name string `json:"name"`
	// ID of the catalog source this server belongs to.
	SourceId *string `json:"source_id,omitempty"`
	// Description of the MCP server and its capabilities.
	Description *string `json:"description,omitempty"`
	// URL to the server's logo image.
	Logo *string `json:"logo,omitempty"`
	// License identifier (SPDX format preferred) under which the MCP server is distributed.
	License *string `json:"license,omitempty"`
	// URL to the full license text or license file.
	LicenseLink *string `json:"license_link,omitempty"`
	// Organization or entity that provides the MCP server.
	Provider *string `json:"provider,omitempty"`
	// Version of the MCP server.
	Version *string `json:"version,omitempty"`
	// Tags for categorizing and filtering MCP servers.
	Tags []string `json:"tags,omitempty"`
	// List of tools exposed by this MCP server.
	Tools              []McpTool             `json:"tools,omitempty"`
	SecurityIndicators *McpSecurityIndicator `json:"securityIndicators,omitempty"`
	// URL to the server's documentation.
	DocumentationUrl *string `json:"documentationUrl,omitempty"`
	// URL to the server's source repository.
	RepositoryUrl *string `json:"repositoryUrl,omitempty"`
	// Source code repository identifier (e.g., GitHub org/repo).
	SourceCode *string `json:"sourceCode,omitempty"`
	// When the server was last updated.
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// When the server was first published.
	PublishedDate *string `json:"publishedDate,omitempty"`
	// Artifacts for this MCP server (e.g., OCI images for local deployments).
	Artifacts []McpArtifact `json:"artifacts,omitempty"`
	// Supported transport types. For remote servers, this is derived from available endpoints.
	Transports []McpTransportType `json:"transports,omitempty"`
	// Full README content in Markdown format.
	Readme         *string            `json:"readme,omitempty"`
	DeploymentMode *McpDeploymentMode `json:"deploymentMode,omitempty"`
	Endpoints      *McpEndpoints      `json:"endpoints,omitempty"`
	// User provided custom properties which are not defined by its type. Following the Model Registry pattern, tags are stored as MetadataStringValue entries with empty string_value, and security indicators are stored as MetadataBoolValue entries.
	CustomProperties map[string]MetadataValue `json:"customProperties,omitempty"`
}

type _McpServer McpServer

// NewMcpServer instantiates a new McpServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpServer(id string, name string) *McpServer {
	this := McpServer{}
	this.Id = id
	this.Name = name
	var deploymentMode McpDeploymentMode = MCPDEPLOYMENTMODE_LOCAL
	this.DeploymentMode = &deploymentMode
	return &this
}

// NewMcpServerWithDefaults instantiates a new McpServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpServerWithDefaults() *McpServer {
	this := McpServer{}
	var deploymentMode McpDeploymentMode = MCPDEPLOYMENTMODE_LOCAL
	this.DeploymentMode = &deploymentMode
	return &this
}

// GetId returns the Id field value
func (o *McpServer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *McpServer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *McpServer) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *McpServer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *McpServer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *McpServer) SetName(v string) {
	o.Name = v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *McpServer) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *McpServer) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *McpServer) SetSourceId(v string) {
	o.SourceId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *McpServer) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *McpServer) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *McpServer) SetDescription(v string) {
	o.Description = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *McpServer) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *McpServer) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *McpServer) SetLogo(v string) {
	o.Logo = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *McpServer) GetLicense() string {
	if o == nil || IsNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetLicenseOk() (*string, bool) {
	if o == nil || IsNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *McpServer) HasLicense() bool {
	if o != nil && !IsNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *McpServer) SetLicense(v string) {
	o.License = &v
}

// GetLicenseLink returns the LicenseLink field value if set, zero value otherwise.
func (o *McpServer) GetLicenseLink() string {
	if o == nil || IsNil(o.LicenseLink) {
		var ret string
		return ret
	}
	return *o.LicenseLink
}

// GetLicenseLinkOk returns a tuple with the LicenseLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetLicenseLinkOk() (*string, bool) {
	if o == nil || IsNil(o.LicenseLink) {
		return nil, false
	}
	return o.LicenseLink, true
}

// HasLicenseLink returns a boolean if a field has been set.
func (o *McpServer) HasLicenseLink() bool {
	if o != nil && !IsNil(o.LicenseLink) {
		return true
	}

	return false
}

// SetLicenseLink gets a reference to the given string and assigns it to the LicenseLink field.
func (o *McpServer) SetLicenseLink(v string) {
	o.LicenseLink = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *McpServer) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *McpServer) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *McpServer) SetProvider(v string) {
	o.Provider = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *McpServer) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *McpServer) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *McpServer) SetVersion(v string) {
	o.Version = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *McpServer) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *McpServer) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *McpServer) SetTags(v []string) {
	o.Tags = v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *McpServer) GetTools() []McpTool {
	if o == nil || IsNil(o.Tools) {
		var ret []McpTool
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetToolsOk() ([]McpTool, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *McpServer) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []McpTool and assigns it to the Tools field.
func (o *McpServer) SetTools(v []McpTool) {
	o.Tools = v
}

// GetSecurityIndicators returns the SecurityIndicators field value if set, zero value otherwise.
func (o *McpServer) GetSecurityIndicators() McpSecurityIndicator {
	if o == nil || IsNil(o.SecurityIndicators) {
		var ret McpSecurityIndicator
		return ret
	}
	return *o.SecurityIndicators
}

// GetSecurityIndicatorsOk returns a tuple with the SecurityIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetSecurityIndicatorsOk() (*McpSecurityIndicator, bool) {
	if o == nil || IsNil(o.SecurityIndicators) {
		return nil, false
	}
	return o.SecurityIndicators, true
}

// HasSecurityIndicators returns a boolean if a field has been set.
func (o *McpServer) HasSecurityIndicators() bool {
	if o != nil && !IsNil(o.SecurityIndicators) {
		return true
	}

	return false
}

// SetSecurityIndicators gets a reference to the given McpSecurityIndicator and assigns it to the SecurityIndicators field.
func (o *McpServer) SetSecurityIndicators(v McpSecurityIndicator) {
	o.SecurityIndicators = &v
}

// GetDocumentationUrl returns the DocumentationUrl field value if set, zero value otherwise.
func (o *McpServer) GetDocumentationUrl() string {
	if o == nil || IsNil(o.DocumentationUrl) {
		var ret string
		return ret
	}
	return *o.DocumentationUrl
}

// GetDocumentationUrlOk returns a tuple with the DocumentationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetDocumentationUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentationUrl) {
		return nil, false
	}
	return o.DocumentationUrl, true
}

// HasDocumentationUrl returns a boolean if a field has been set.
func (o *McpServer) HasDocumentationUrl() bool {
	if o != nil && !IsNil(o.DocumentationUrl) {
		return true
	}

	return false
}

// SetDocumentationUrl gets a reference to the given string and assigns it to the DocumentationUrl field.
func (o *McpServer) SetDocumentationUrl(v string) {
	o.DocumentationUrl = &v
}

// GetRepositoryUrl returns the RepositoryUrl field value if set, zero value otherwise.
func (o *McpServer) GetRepositoryUrl() string {
	if o == nil || IsNil(o.RepositoryUrl) {
		var ret string
		return ret
	}
	return *o.RepositoryUrl
}

// GetRepositoryUrlOk returns a tuple with the RepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetRepositoryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryUrl) {
		return nil, false
	}
	return o.RepositoryUrl, true
}

// HasRepositoryUrl returns a boolean if a field has been set.
func (o *McpServer) HasRepositoryUrl() bool {
	if o != nil && !IsNil(o.RepositoryUrl) {
		return true
	}

	return false
}

// SetRepositoryUrl gets a reference to the given string and assigns it to the RepositoryUrl field.
func (o *McpServer) SetRepositoryUrl(v string) {
	o.RepositoryUrl = &v
}

// GetSourceCode returns the SourceCode field value if set, zero value otherwise.
func (o *McpServer) GetSourceCode() string {
	if o == nil || IsNil(o.SourceCode) {
		var ret string
		return ret
	}
	return *o.SourceCode
}

// GetSourceCodeOk returns a tuple with the SourceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetSourceCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceCode) {
		return nil, false
	}
	return o.SourceCode, true
}

// HasSourceCode returns a boolean if a field has been set.
func (o *McpServer) HasSourceCode() bool {
	if o != nil && !IsNil(o.SourceCode) {
		return true
	}

	return false
}

// SetSourceCode gets a reference to the given string and assigns it to the SourceCode field.
func (o *McpServer) SetSourceCode(v string) {
	o.SourceCode = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *McpServer) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *McpServer) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *McpServer) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetPublishedDate returns the PublishedDate field value if set, zero value otherwise.
func (o *McpServer) GetPublishedDate() string {
	if o == nil || IsNil(o.PublishedDate) {
		var ret string
		return ret
	}
	return *o.PublishedDate
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetPublishedDateOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedDate) {
		return nil, false
	}
	return o.PublishedDate, true
}

// HasPublishedDate returns a boolean if a field has been set.
func (o *McpServer) HasPublishedDate() bool {
	if o != nil && !IsNil(o.PublishedDate) {
		return true
	}

	return false
}

// SetPublishedDate gets a reference to the given string and assigns it to the PublishedDate field.
func (o *McpServer) SetPublishedDate(v string) {
	o.PublishedDate = &v
}

// GetArtifacts returns the Artifacts field value if set, zero value otherwise.
func (o *McpServer) GetArtifacts() []McpArtifact {
	if o == nil || IsNil(o.Artifacts) {
		var ret []McpArtifact
		return ret
	}
	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetArtifactsOk() ([]McpArtifact, bool) {
	if o == nil || IsNil(o.Artifacts) {
		return nil, false
	}
	return o.Artifacts, true
}

// HasArtifacts returns a boolean if a field has been set.
func (o *McpServer) HasArtifacts() bool {
	if o != nil && !IsNil(o.Artifacts) {
		return true
	}

	return false
}

// SetArtifacts gets a reference to the given []McpArtifact and assigns it to the Artifacts field.
func (o *McpServer) SetArtifacts(v []McpArtifact) {
	o.Artifacts = v
}

// GetTransports returns the Transports field value if set, zero value otherwise.
func (o *McpServer) GetTransports() []McpTransportType {
	if o == nil || IsNil(o.Transports) {
		var ret []McpTransportType
		return ret
	}
	return o.Transports
}

// GetTransportsOk returns a tuple with the Transports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetTransportsOk() ([]McpTransportType, bool) {
	if o == nil || IsNil(o.Transports) {
		return nil, false
	}
	return o.Transports, true
}

// HasTransports returns a boolean if a field has been set.
func (o *McpServer) HasTransports() bool {
	if o != nil && !IsNil(o.Transports) {
		return true
	}

	return false
}

// SetTransports gets a reference to the given []McpTransportType and assigns it to the Transports field.
func (o *McpServer) SetTransports(v []McpTransportType) {
	o.Transports = v
}

// GetReadme returns the Readme field value if set, zero value otherwise.
func (o *McpServer) GetReadme() string {
	if o == nil || IsNil(o.Readme) {
		var ret string
		return ret
	}
	return *o.Readme
}

// GetReadmeOk returns a tuple with the Readme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetReadmeOk() (*string, bool) {
	if o == nil || IsNil(o.Readme) {
		return nil, false
	}
	return o.Readme, true
}

// HasReadme returns a boolean if a field has been set.
func (o *McpServer) HasReadme() bool {
	if o != nil && !IsNil(o.Readme) {
		return true
	}

	return false
}

// SetReadme gets a reference to the given string and assigns it to the Readme field.
func (o *McpServer) SetReadme(v string) {
	o.Readme = &v
}

// GetDeploymentMode returns the DeploymentMode field value if set, zero value otherwise.
func (o *McpServer) GetDeploymentMode() McpDeploymentMode {
	if o == nil || IsNil(o.DeploymentMode) {
		var ret McpDeploymentMode
		return ret
	}
	return *o.DeploymentMode
}

// GetDeploymentModeOk returns a tuple with the DeploymentMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetDeploymentModeOk() (*McpDeploymentMode, bool) {
	if o == nil || IsNil(o.DeploymentMode) {
		return nil, false
	}
	return o.DeploymentMode, true
}

// HasDeploymentMode returns a boolean if a field has been set.
func (o *McpServer) HasDeploymentMode() bool {
	if o != nil && !IsNil(o.DeploymentMode) {
		return true
	}

	return false
}

// SetDeploymentMode gets a reference to the given McpDeploymentMode and assigns it to the DeploymentMode field.
func (o *McpServer) SetDeploymentMode(v McpDeploymentMode) {
	o.DeploymentMode = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *McpServer) GetEndpoints() McpEndpoints {
	if o == nil || IsNil(o.Endpoints) {
		var ret McpEndpoints
		return ret
	}
	return *o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetEndpointsOk() (*McpEndpoints, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *McpServer) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given McpEndpoints and assigns it to the Endpoints field.
func (o *McpServer) SetEndpoints(v McpEndpoints) {
	o.Endpoints = &v
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *McpServer) GetCustomProperties() map[string]MetadataValue {
	if o == nil || IsNil(o.CustomProperties) {
		var ret map[string]MetadataValue
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpServer) GetCustomPropertiesOk() (map[string]MetadataValue, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return map[string]MetadataValue{}, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *McpServer) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given map[string]MetadataValue and assigns it to the CustomProperties field.
func (o *McpServer) SetCustomProperties(v map[string]MetadataValue) {
	o.CustomProperties = v
}

func (o McpServer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !IsNil(o.LicenseLink) {
		toSerialize["license_link"] = o.LicenseLink
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	if !IsNil(o.SecurityIndicators) {
		toSerialize["securityIndicators"] = o.SecurityIndicators
	}
	if !IsNil(o.DocumentationUrl) {
		toSerialize["documentationUrl"] = o.DocumentationUrl
	}
	if !IsNil(o.RepositoryUrl) {
		toSerialize["repositoryUrl"] = o.RepositoryUrl
	}
	if !IsNil(o.SourceCode) {
		toSerialize["sourceCode"] = o.SourceCode
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.PublishedDate) {
		toSerialize["publishedDate"] = o.PublishedDate
	}
	if !IsNil(o.Artifacts) {
		toSerialize["artifacts"] = o.Artifacts
	}
	if !IsNil(o.Transports) {
		toSerialize["transports"] = o.Transports
	}
	if !IsNil(o.Readme) {
		toSerialize["readme"] = o.Readme
	}
	if !IsNil(o.DeploymentMode) {
		toSerialize["deploymentMode"] = o.DeploymentMode
	}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	return toSerialize, nil
}

type NullableMcpServer struct {
	value *McpServer
	isSet bool
}

func (v NullableMcpServer) Get() *McpServer {
	return v.value
}

func (v *NullableMcpServer) Set(val *McpServer) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpServer) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpServer(val *McpServer) *NullableMcpServer {
	return &NullableMcpServer{value: val, isSet: true}
}

func (v NullableMcpServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
