/*
Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the McpToolParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpToolParameter{}

// McpToolParameter Metadata describing a single MCP tool parameter.
type McpToolParameter struct {
	// Parameter name.
	Name string `json:"name"`
	// Parameter type.
	Type string `json:"type"`
	// Whether this parameter is required.
	Required bool `json:"required"`
	// Parameter purpose.
	Description *string `json:"description,omitempty"`
}

type _McpToolParameter McpToolParameter

// NewMcpToolParameter instantiates a new McpToolParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpToolParameter(name string, type_ string, required bool) *McpToolParameter {
	this := McpToolParameter{}
	this.Name = name
	this.Type = type_
	this.Required = required
	return &this
}

// NewMcpToolParameterWithDefaults instantiates a new McpToolParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpToolParameterWithDefaults() *McpToolParameter {
	this := McpToolParameter{}
	return &this
}

// GetName returns the Name field value
func (o *McpToolParameter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *McpToolParameter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *McpToolParameter) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *McpToolParameter) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *McpToolParameter) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *McpToolParameter) SetType(v string) {
	o.Type = v
}

// GetRequired returns the Required field value
func (o *McpToolParameter) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *McpToolParameter) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *McpToolParameter) SetRequired(v bool) {
	o.Required = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *McpToolParameter) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpToolParameter) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *McpToolParameter) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *McpToolParameter) SetDescription(v string) {
	o.Description = &v
}

func (o McpToolParameter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpToolParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["required"] = o.Required
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableMcpToolParameter struct {
	value *McpToolParameter
	isSet bool
}

func (v NullableMcpToolParameter) Get() *McpToolParameter {
	return v.value
}

func (v *NullableMcpToolParameter) Set(val *McpToolParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpToolParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpToolParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpToolParameter(val *McpToolParameter) *NullableMcpToolParameter {
	return &NullableMcpToolParameter{value: val, isSet: true}
}

func (v NullableMcpToolParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpToolParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
