/*
Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the McpArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpArtifact{}

// McpArtifact Artifact metadata for local MCP server deployment.
type McpArtifact struct {
	// OCI image URI for local deployment.
	Uri string `json:"uri"`
}

type _McpArtifact McpArtifact

// NewMcpArtifact instantiates a new McpArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpArtifact(uri string) *McpArtifact {
	this := McpArtifact{}
	this.Uri = uri
	return &this
}

// NewMcpArtifactWithDefaults instantiates a new McpArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpArtifactWithDefaults() *McpArtifact {
	this := McpArtifact{}
	return &this
}

// GetUri returns the Uri field value
func (o *McpArtifact) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *McpArtifact) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *McpArtifact) SetUri(v string) {
	o.Uri = v
}

func (o McpArtifact) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

type NullableMcpArtifact struct {
	value *McpArtifact
	isSet bool
}

func (v NullableMcpArtifact) Get() *McpArtifact {
	return v.value
}

func (v *NullableMcpArtifact) Set(val *McpArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpArtifact(val *McpArtifact) *NullableMcpArtifact {
	return &NullableMcpArtifact{value: val, isSet: true}
}

func (v NullableMcpArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
