/*
Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the McpEnvVarMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpEnvVarMetadata{}

// McpEnvVarMetadata struct for McpEnvVarMetadata
type McpEnvVarMetadata struct {
	// Environment variable name
	Name string `json:"name"`
	// Purpose and usage of this variable
	Description string `json:"description"`
	// Whether this variable must be set
	Required *bool `json:"required,omitempty"`
	// Default value if not provided. Only for optional variables. Secrets should NEVER have default values.
	DefaultValue *string `json:"defaultValue,omitempty"`
	// Expected variable type
	Type *string `json:"type,omitempty"`
	// Example value for documentation purposes
	Example *string `json:"example,omitempty"`
}

type _McpEnvVarMetadata McpEnvVarMetadata

// NewMcpEnvVarMetadata instantiates a new McpEnvVarMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpEnvVarMetadata(name string, description string) *McpEnvVarMetadata {
	this := McpEnvVarMetadata{}
	this.Name = name
	this.Description = description
	var required bool = false
	this.Required = &required
	var type_ string = "string"
	this.Type = &type_
	return &this
}

// NewMcpEnvVarMetadataWithDefaults instantiates a new McpEnvVarMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpEnvVarMetadataWithDefaults() *McpEnvVarMetadata {
	this := McpEnvVarMetadata{}
	var required bool = false
	this.Required = &required
	var type_ string = "string"
	this.Type = &type_
	return &this
}

// GetName returns the Name field value
func (o *McpEnvVarMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *McpEnvVarMetadata) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *McpEnvVarMetadata) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *McpEnvVarMetadata) SetDescription(v string) {
	o.Description = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *McpEnvVarMetadata) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *McpEnvVarMetadata) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *McpEnvVarMetadata) SetRequired(v bool) {
	o.Required = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *McpEnvVarMetadata) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue) {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetDefaultValueOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *McpEnvVarMetadata) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *McpEnvVarMetadata) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *McpEnvVarMetadata) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *McpEnvVarMetadata) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *McpEnvVarMetadata) SetType(v string) {
	o.Type = &v
}

// GetExample returns the Example field value if set, zero value otherwise.
func (o *McpEnvVarMetadata) GetExample() string {
	if o == nil || IsNil(o.Example) {
		var ret string
		return ret
	}
	return *o.Example
}

// GetExampleOk returns a tuple with the Example field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McpEnvVarMetadata) GetExampleOk() (*string, bool) {
	if o == nil || IsNil(o.Example) {
		return nil, false
	}
	return o.Example, true
}

// HasExample returns a boolean if a field has been set.
func (o *McpEnvVarMetadata) HasExample() bool {
	if o != nil && !IsNil(o.Example) {
		return true
	}

	return false
}

// SetExample gets a reference to the given string and assigns it to the Example field.
func (o *McpEnvVarMetadata) SetExample(v string) {
	o.Example = &v
}

func (o McpEnvVarMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpEnvVarMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Example) {
		toSerialize["example"] = o.Example
	}
	return toSerialize, nil
}

type NullableMcpEnvVarMetadata struct {
	value *McpEnvVarMetadata
	isSet bool
}

func (v NullableMcpEnvVarMetadata) Get() *McpEnvVarMetadata {
	return v.value
}

func (v *NullableMcpEnvVarMetadata) Set(val *McpEnvVarMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpEnvVarMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpEnvVarMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpEnvVarMetadata(val *McpEnvVarMetadata) *NullableMcpEnvVarMetadata {
	return &NullableMcpEnvVarMetadata{value: val, isSet: true}
}

func (v NullableMcpEnvVarMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpEnvVarMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
