/*
Model Catalog REST API

REST API for Model Registry to create and manage ML model metadata

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CatalogAssetType the model 'CatalogAssetType'
type CatalogAssetType string

// List of CatalogAssetType
const (
	CATALOGASSETTYPE_MODELS      CatalogAssetType = "models"
	CATALOGASSETTYPE_MCP_SERVERS CatalogAssetType = "mcp_servers"
)

// All allowed values of CatalogAssetType enum
var AllowedCatalogAssetTypeEnumValues = []CatalogAssetType{
	"models",
	"mcp_servers",
}

func (v *CatalogAssetType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CatalogAssetType(value)
	for _, existing := range AllowedCatalogAssetTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CatalogAssetType", value)
}

// NewCatalogAssetTypeFromValue returns a pointer to a valid CatalogAssetType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCatalogAssetTypeFromValue(v string) (*CatalogAssetType, error) {
	ev := CatalogAssetType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CatalogAssetType: valid values are %v", v, AllowedCatalogAssetTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CatalogAssetType) IsValid() bool {
	for _, existing := range AllowedCatalogAssetTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CatalogAssetType value
func (v CatalogAssetType) Ptr() *CatalogAssetType {
	return &v
}

type NullableCatalogAssetType struct {
	value *CatalogAssetType
	isSet bool
}

func (v NullableCatalogAssetType) Get() *CatalogAssetType {
	return v.value
}

func (v *NullableCatalogAssetType) Set(val *CatalogAssetType) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogAssetType) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogAssetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogAssetType(val *CatalogAssetType) *NullableCatalogAssetType {
	return &NullableCatalogAssetType{value: val, isSet: true}
}

func (v NullableCatalogAssetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogAssetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
