---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: ACCESS_KEY_ID
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: SECRET_KEY
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Wait a few seconds for MinIO to be up and running.
            sleep 5
            # Configure alias 'local' for our MinIO instance.
            mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
            # Create a default bucket named "default-bucket". If it already exists, ignore the error.
            mc mb local/default || true
