apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  ACCESS_KEY_ID: "minioadmin"  
  SECRET_KEY: "minioadmin"   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
          - server
          - /data
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: ACCESS_KEY_ID
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: SECRET_KEY
        ports:
          - containerPort: 9000
            name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
