// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Model Catalog REST API
 *
 * REST API for Model Registry to create and manage ML model metadata
 *
 * API version: v1alpha1
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	model "github.com/kubeflow/model-registry/catalog/pkg/openapi"
)

// McpCatalogServiceAPIController binds http requests to an api service and writes the service results to the http response
type McpCatalogServiceAPIController struct {
	service      McpCatalogServiceAPIServicer
	errorHandler ErrorHandler
}

// McpCatalogServiceAPIOption for how the controller is set up.
type McpCatalogServiceAPIOption func(*McpCatalogServiceAPIController)

// WithMcpCatalogServiceAPIErrorHandler inject ErrorHandler into controller
func WithMcpCatalogServiceAPIErrorHandler(h ErrorHandler) McpCatalogServiceAPIOption {
	return func(c *McpCatalogServiceAPIController) {
		c.errorHandler = h
	}
}

// NewMcpCatalogServiceAPIController creates a default api controller
func NewMcpCatalogServiceAPIController(s McpCatalogServiceAPIServicer, opts ...McpCatalogServiceAPIOption) *McpCatalogServiceAPIController {
	controller := &McpCatalogServiceAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the McpCatalogServiceAPIController
func (c *McpCatalogServiceAPIController) Routes() Routes {
	return Routes{
		"FindMcpServers": Route{
			"FindMcpServers",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers",
			c.FindMcpServers,
		},
		"FindMcpServersFilterOptions": Route{
			"FindMcpServersFilterOptions",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers/filter_options",
			c.FindMcpServersFilterOptions,
		},
		"GetMcpServer": Route{
			"GetMcpServer",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers/{server_id}",
			c.GetMcpServer,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the McpCatalogServiceAPIController
func (c *McpCatalogServiceAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"FindMcpServers",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers",
			c.FindMcpServers,
		},
		Route{
			"FindMcpServersFilterOptions",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers/filter_options",
			c.FindMcpServersFilterOptions,
		},
		Route{
			"GetMcpServer",
			strings.ToUpper("Get"),
			"/api/model_catalog/v1alpha1/mcp_servers/{server_id}",
			c.GetMcpServer,
		},
	}
}

// FindMcpServers - List All McpServers
func (c *McpCatalogServiceAPIController) FindMcpServers(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nameParam string
	if query.Has("name") {
		param := query.Get("name")

		nameParam = param
	} else {
	}
	var qParam string
	if query.Has("q") {
		param := query.Get("q")

		qParam = param
	} else {
	}
	var filterQueryParam string
	if query.Has("filterQuery") {
		param := query.Get("filterQuery")

		filterQueryParam = param
	} else {
	}
	var namedQueryParam string
	if query.Has("namedQuery") {
		param := query.Get("namedQuery")

		namedQueryParam = param
	} else {
	}
	var pageSizeParam string
	if query.Has("pageSize") {
		param := query.Get("pageSize")

		pageSizeParam = param
	} else {
	}
	var orderByParam model.OrderByField
	if query.Has("orderBy") {
		param := model.OrderByField(query.Get("orderBy"))

		orderByParam = param
	} else {
	}
	var sortOrderParam model.SortOrder
	if query.Has("sortOrder") {
		param := model.SortOrder(query.Get("sortOrder"))

		sortOrderParam = param
	} else {
	}
	var nextPageTokenParam string
	if query.Has("nextPageToken") {
		param := query.Get("nextPageToken")

		nextPageTokenParam = param
	} else {
	}
	result, err := c.service.FindMcpServers(r.Context(), nameParam, qParam, filterQueryParam, namedQueryParam, pageSizeParam, orderByParam, sortOrderParam, nextPageTokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// FindMcpServersFilterOptions - Lists fields and available options that can be used in `filterQuery` on the list MCP servers endpoint.
func (c *McpCatalogServiceAPIController) FindMcpServersFilterOptions(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.FindMcpServersFilterOptions(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetMcpServer - Get an McpServer
func (c *McpCatalogServiceAPIController) GetMcpServer(w http.ResponseWriter, r *http.Request) {
	serverIdParam := chi.URLParam(r, "server_id")
	if serverIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"server_id"}, nil)
		return
	}
	result, err := c.service.GetMcpServer(r.Context(), serverIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
