apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- virtual-service.yaml
- destination-rule-ui.yaml
- destination-rule-bff.yaml
- authorization-policy-ui.yaml
- authorization-policy-bff.yaml

patchesJson6902:
  - path: model-registry-ui-service.yaml
    target:
      version: v1
      kind: Service
      name: model-registry-ui-service