# coding: utf-8

# flake8: noqa
"""
Model Registry REST API

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from mr_openapi.models.artifact import Artifact
from mr_openapi.models.artifact_create import ArtifactCreate
from mr_openapi.models.artifact_list import ArtifactList
from mr_openapi.models.artifact_state import ArtifactState
from mr_openapi.models.artifact_type_query_param import ArtifactTypeQueryParam
from mr_openapi.models.artifact_update import ArtifactUpdate
from mr_openapi.models.base_artifact import BaseArtifact
from mr_openapi.models.base_model import BaseModel
from mr_openapi.models.base_resource import BaseResource
from mr_openapi.models.base_resource_create import BaseResourceCreate
from mr_openapi.models.base_resource_dates import BaseResourceDates
from mr_openapi.models.base_resource_list import BaseResourceList
from mr_openapi.models.base_resource_update import BaseResourceUpdate
from mr_openapi.models.data_set import DataSet
from mr_openapi.models.data_set_create import DataSetCreate
from mr_openapi.models.data_set_update import DataSetUpdate
from mr_openapi.models.doc_artifact import DocArtifact
from mr_openapi.models.doc_artifact_create import DocArtifactCreate
from mr_openapi.models.doc_artifact_update import DocArtifactUpdate
from mr_openapi.models.error import Error
from mr_openapi.models.execution_state import ExecutionState
from mr_openapi.models.experiment import Experiment
from mr_openapi.models.experiment_create import ExperimentCreate
from mr_openapi.models.experiment_list import ExperimentList
from mr_openapi.models.experiment_run import ExperimentRun
from mr_openapi.models.experiment_run_create import ExperimentRunCreate
from mr_openapi.models.experiment_run_list import ExperimentRunList
from mr_openapi.models.experiment_run_state import ExperimentRunState
from mr_openapi.models.experiment_run_status import ExperimentRunStatus
from mr_openapi.models.experiment_run_update import ExperimentRunUpdate
from mr_openapi.models.experiment_state import ExperimentState
from mr_openapi.models.experiment_update import ExperimentUpdate
from mr_openapi.models.inference_service import InferenceService
from mr_openapi.models.inference_service_create import InferenceServiceCreate
from mr_openapi.models.inference_service_list import InferenceServiceList
from mr_openapi.models.inference_service_state import InferenceServiceState
from mr_openapi.models.inference_service_update import InferenceServiceUpdate
from mr_openapi.models.metadata_bool_value import MetadataBoolValue
from mr_openapi.models.metadata_double_value import MetadataDoubleValue
from mr_openapi.models.metadata_int_value import MetadataIntValue
from mr_openapi.models.metadata_proto_value import MetadataProtoValue
from mr_openapi.models.metadata_string_value import MetadataStringValue
from mr_openapi.models.metadata_struct_value import MetadataStructValue
from mr_openapi.models.metadata_value import MetadataValue
from mr_openapi.models.metric import Metric
from mr_openapi.models.metric_create import MetricCreate
from mr_openapi.models.metric_list import MetricList
from mr_openapi.models.metric_update import MetricUpdate
from mr_openapi.models.model_artifact import ModelArtifact
from mr_openapi.models.model_artifact_create import ModelArtifactCreate
from mr_openapi.models.model_artifact_list import ModelArtifactList
from mr_openapi.models.model_artifact_update import ModelArtifactUpdate
from mr_openapi.models.model_version import ModelVersion
from mr_openapi.models.model_version_create import ModelVersionCreate
from mr_openapi.models.model_version_list import ModelVersionList
from mr_openapi.models.model_version_state import ModelVersionState
from mr_openapi.models.model_version_update import ModelVersionUpdate
from mr_openapi.models.order_by_field import OrderByField
from mr_openapi.models.parameter import Parameter
from mr_openapi.models.parameter_create import ParameterCreate
from mr_openapi.models.parameter_type import ParameterType
from mr_openapi.models.parameter_update import ParameterUpdate
from mr_openapi.models.registered_model import RegisteredModel
from mr_openapi.models.registered_model_create import RegisteredModelCreate
from mr_openapi.models.registered_model_list import RegisteredModelList
from mr_openapi.models.registered_model_state import RegisteredModelState
from mr_openapi.models.registered_model_update import RegisteredModelUpdate
from mr_openapi.models.serve_model import ServeModel
from mr_openapi.models.serve_model_create import ServeModelCreate
from mr_openapi.models.serve_model_list import ServeModelList
from mr_openapi.models.serve_model_update import ServeModelUpdate
from mr_openapi.models.serving_environment import ServingEnvironment
from mr_openapi.models.serving_environment_create import ServingEnvironmentCreate
from mr_openapi.models.serving_environment_list import ServingEnvironmentList
from mr_openapi.models.serving_environment_update import ServingEnvironmentUpdate
from mr_openapi.models.sort_order import SortOrder
