"""Model Registry REST API.

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ArtifactTypeQueryParam(str, Enum):
    """Supported artifact types for querying."""

    """
    allowed enum values
    """
    MODEL_MINUS_ARTIFACT = "model-artifact"
    DOC_MINUS_ARTIFACT = "doc-artifact"
    DATASET_MINUS_ARTIFACT = "dataset-artifact"
    METRIC = "metric"
    PARAMETER = "parameter"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ArtifactTypeQueryParam from a JSON string."""
        return cls(json.loads(json_str))
