"""Model Registry REST API.

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class MetadataIntValue(BaseModel):
    """An integer (int32) property value."""  # noqa: E501

    int_value: Annotated[str, Field(strict=True)]
    metadata_type: StrictStr = Field(alias="metadataType")
    __properties: ClassVar[list[str]] = ["int_value", "metadataType"]

    @field_validator("int_value")
    def int_value_validate_regular_expression(cls, value):
        """Validates the regular expression."""
        if not re.match(r"^-?([1-9][0-9]{0,8}|0)$", value):
            msg = r"must validate the regular expression /^-?([1-9][0-9]{0,8}|0)$/"
            raise ValueError(msg)
        return value

    @field_validator("metadata_type")
    def metadata_type_validate_enum(cls, value):
        """Validates the enum."""
        if value not in {"MetadataIntValue"}:
            msg = "must be one of enum values ('MetadataIntValue')"
            raise ValueError(msg)
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias."""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias."""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of MetadataIntValue from a JSON string."""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        return self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of MetadataIntValue from a dict."""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        return cls.model_validate(
            {
                "int_value": obj.get("int_value"),
                "metadataType": obj.get("metadataType") if obj.get("metadataType") is not None else "MetadataIntValue",
            }
        )
