apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-registry-bff-role.yaml
  - model-registry-bff-service.yaml
  - model-registry-bff-deployment.yaml
  - model-registry-ui-service.yaml
  - model-registry-ui-deployment.yaml
  - model-registry-service-account.yaml

images:
  - name: model-registry-ui-image
    newName: kubeflow/model-registry-ui:latest
  - name: model-registry-bff-image
    newName: kubeflow/model-registry-bff:latest
