apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- model-registry-bff-role.yaml
- model-registry-bff-service.yaml
- model-registry-bff-deployment.yaml
- model-registry-bff-service-account.yaml
- model-registry-ui-service.yaml
- model-registry-ui-deployment.yaml

images:
- name: model-registry-ui-image
  newName: docker.io/kubeflow/model-registry-ui
  newTag: latest
- name: model-registry-bff-image
  newName: docker.io/kubeflow/model-registry-bff
  newTag: latest
