apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-ui
  labels:
    app: model-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-registry-ui
  template:
    metadata:
      labels:
        app: model-registry-ui
    spec:
      containers:
      - name: model-registry-ui
        image: model-registry-ui-image
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
          - containerPort: 8080
        env:
          - name: API_URL
            value: "http://model-registry-bff-service:4000"
