apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: model-registry-test-source-subscription
  namespace: openshift-operators
spec:
  channel: fast
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace