apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: mr-initializer
spec:
  container:
    name: storage-initializer
    image: quay.io/kubeflow/model-registry-storage-initializer:latest
    env:
    - name: MR_BASE_URL
      value: "modelregistry-sample.kubeflow.svc.cluster.local:8080"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
  supportedUriFormats:
    - prefix: model-registry://
