// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameAssociation = "association"

// Association mapped from table <association>
type Association struct {
	ID          int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ContextID   int32 `gorm:"column:context_id;not null" json:"context_id"`
	ExecutionID int32 `gorm:"column:execution_id;not null" json:"execution_id"`
}

// TableName Association's table name
func (*Association) TableName() string {
	return TableNameAssociation
}
