// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameAttribution = "Attribution"

// Attribution mapped from table <Attribution>
type Attribution struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ContextID  int32 `gorm:"column:context_id;not null" json:"context_id"`
	ArtifactID int32 `gorm:"column:artifact_id;not null" json:"artifact_id"`
}

// TableName Attribution's table name
func (*Attribution) TableName() string {
	return TableNameAttribution
}
