name: Validate OpenAPI spec
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "api/openapi/model-registry.yaml"

permissions: # set contents: read at top-level, per OpenSSF ScoreCard rule TokenPermissionsID
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Validate OpenAPI spec
        run: |
          make openapi/validate
