name: Test container image build and deployment
on:
  workflow_dispatch:
  pull_request:
jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Remove AppArmor profile for mysql in KinD on GHA # https://github.com/kubeflow/manifests/issues/2507
        run: |
          set -x
          # sudo apt-get install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

